config/routes.rb
BloggingOnRails::Application.routes.draw do
  ActiveAdmin.routes(self)

  root to: "home#index"
  get "/tag_cloud" => 'home#tag_cloud'
  get 'tags/:tag', to: 'home#index', as: :tag

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create]
  end

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class AdminUser < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  category_id :integer
#  name        :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  parent_id   :integer
#

class Category < ActiveRecord::Base

  # attr_accessible :name

  validates :name, presence: true

  belongs_to :parent, class_name: "Category"
  has_many :children, class_name: "Category", foreign_key: "parent_id"

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  author     :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  post_id    :integer
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base

  belongs_to :post

  validates :author, presence: true
  validates :email, presence: true
  validates :content, presence: true
  validates :post_id, presence: true

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :string(255)
#  status     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base

  # attr_accessible :content, :status, :title, :tag_list

  acts_as_taggable

  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
  validates :status, presence: true

  # belongs_to :category
  has_many :comments, dependent: :destroy

  default_scope order: 'posts.created_at DESC'

  scope :unpublished, where(status: "Draft")
  scope :published, where(status: "Published")

  def self.published
    Post.where(status: "Published")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)

    if @comment.save
      flash[:success] = "Comment created!"
    else
      flash[:error] = "Comment failed!"
    end

    redirect_to @post
  end

private

  def comment_params
    params.require(:comment).permit(:author, :content, :email)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.published
    end
  end

  def tag_cloud
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.published
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Blogging On Rails"

    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<li>
  <span class="author">
    Name: <%= comment.author %>
  </span>

  <span class="content">
    <%= comment.content %>
  </span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
  </span>
</li>

app/views/home/index.html.erb
<div class="well">
  <% if @posts.any? %>
    <ul class="list-styling">
      <%= render @posts %>
    </ul>
  <% else %>
    <h3>No Posts To Display... Yet</h3>
  <% end %>
</div>

app/views/home/tag_cloud.html.erb
<div class="well">
  <div id="tag_cloud">
    <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    By <a href="http://damianmastylo.com/">Damian Mastylo</a> © 2012-2014
  </small>
</footer>

app/views/layouts/_nav_bar.html.erb
<div class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Blogging On Rails", root_path, class: "navbar-brand" %>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Tag Cloud", "/tag_cloud" %></li>
      <li><%= link_to "Admin", "/admin" %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div>

app/views/layouts/_shim.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->
<!--[if gte IE 9]>
    <style type="text/css">
        .gradient {
            filter: none;
        }
    </style>
<![endif]-->

app/views/layouts/_sidebar.html.erb
Sidebar placeholder

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
  </head>
  <body>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

    <%= render 'layouts/nav_bar' %>

    <div class="container">
      <div class="content">
        <div class="row">
          <div class="col-sm-12 col-md-12">
            <%= content_tag(:div, flash[:error], :class => 'alert alert-error', :id => "flash_error") if flash[:error] %>
            <%= content_tag(:div, flash[:notice], :class => 'alert alert-warning', :id => "flash_notice") if flash[:notice] %>
            <%= content_tag(:div, flash[:alert], :class => 'alert alert-info', :id => "flash_alert") if flash[:alert] %>
          </div>
        </div><!--/row -->

        <div class="row">
          <div class="col-sm-8 col-md-8">
            <%= yield %>
          </div>
          <div class="col-sm-4 col-md-4">
            <div class="center well">
              <%= render 'layouts/sidebar' %>
            </div>
          </div>
        </div>
      </div><!--/content -->

      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/posts/_post.html.erb
<li class="post">
  <span class="title">
    <%= link_to post.title, post, class: 'title' %>
  </span>

  <span class="content">
    <%= raw post.content %>
  </span>

  <span class="content">
    Tags: <%= raw post.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(', ') %>
  </span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>

<div class="well">
  <h3><%= @post.title %></h3>

  <%= raw @post.content %>

  <span class="content">
    Tags: <%= raw @post.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(', ') %>
  </span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(@post.created_at) %> ago.
  </span>

  <h4><%= pluralize(@comments.count, "Comments") %></h4>
  <% if @comments.any? %>
    <ul class="list-styling">
      <%= render @comments %>
    </ul>
  <% end %>

  <h4>Leave Comment</h4>
  <%= form_for [@post, Comment.new] do |f| %>
    <%= f.label "Name" %>
    <%= f.text_field :author, class: "input-block-level" %>
    <%= f.label "Email" %>
    <%= f.text_field :email, class: "input-block-level" %>
    <%= f.label "Compose new comment" %>
    <%= f.text_area :content, class: "input-block-level" %>
    <br><%= f.submit "Post", class: "btn btn-block btn-large btn-primary" %>
  <% end %>
</div>